### ISSUE TITLE
Application quits on timeout instead of retrying

### ISSUE THREAD

**Issue by lzrf0cuz** [splitio/split-evaluator#121]
The application quits on timeout instead of retrying. 
The previous versions handled this gracefully.

**Error:** `Client timed out for api key ################################abcd`

**Current Behavior:** `Exit`
**Ideal Behavior:** `Graceful retry`

**Version:** `2.2.0 (Oct 31, 2022)`

**Comment by hbqdev** [comment]
Hi @lzrf0cuz 
Can you please share with us your Evaluator config and any logging you have for this issue?

Thank you and Regards

**Comment by lzrf0cuz** [comment]
**Command:** 
`docker run -e SPLIT_EVALUATOR_API_KEY=KEY -e SPLIT_EVALUATOR_AUTH_TOKEN=TOKEN -e SPLIT_EVALUATOR_LOG_LEVEL=debug -p 7548:7548 splitsoftware/split-evaluator:2.2.0`

**Log:**
split-evaluator@2.2.0 start
node server.js

Setting log level with DEBUG
[DEBUG] splitio => Retrieving default SDK client.
[DEBUG] splitio => sync:split-changes: Spin up split update using since = -1
[INFO]  splitio => sync:streaming: Connecting streaming.
[INFO]  splitio => sync:streaming: Refreshing streaming token in 3000 seconds, and connecting streaming in 60 seconds.
[DEBUG] splitio => sync:split-changes: New splits 253
[DEBUG] splitio => sync:split-changes: Removed splits 0
[DEBUG] splitio => sync:split-changes: Segment names collected 90
[DEBUG] splitio => sync: Running segmentChangesUpdater
[DEBUG] splitio => sync:segment-changes: Started segments update
[DEBUG] splitio => sync:segment-changes: Processing segment ******
...
[DEBUG] splitio => sync:segment-changes: Processed ****** with till = 1670967567418. Added: 11. Removed: 0
...
Client timed out for api key ################################abcd
npm notice
npm notice New major version of npm available! 8.11.0 -> 9.2.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
npm notice Run `npm install -g npm@9.2.0` to update!
npm notice

**Redacted:** `******`
**Skipped:** `...`

**Comment by hbqdev** [comment]
Hi @lzrf0cuz 

It seems you're having issue with that particular API key, can you please try with a different API key and see if that works?

Please make sure you are using the client API key and not server API key.

Regards

**Comment by hbqdev** [comment]
Hi @lzrf0cuz 

In addition, we want to let you know that the process gracefully exiting is the correct behavior, since the timeout is, in most scenarios, not a retriable error. It could happen because of an incorrect API key, in which case it will time out every time, or because the data to be fetched cannot be fetched in the default 10 seconds (which is likely what's happening here), in which case odds are the retries will time out as well.
  
Also, please share with us the first 4 letters of the API key you are using, or the workspace/environment names. We'd like to look into the data in your env to figure out why the Evaluator is not able to etch the data in 10 seconds or less.

If possible, you can send an email to support@split.io so that we can better assist you.

Regards,

**Comment by hbqdev** [comment]
Hi @lzrf0cuz 

Our engineering team will expose the config so that you can change the timeout value through an environment variable, which we hope will fix this issue.

We will update you once the new feature is available

Regards

**Comment by emmaz90** [comment]
Hi @lzrf0cuz 

We just released 2.3.0 version where you can use the environment variable _**SPLIT_EVALUATOR_GLOBAL_CONFIG**_ to configure split client properties.

With _startup.readyTimeout_ you can set the maximum amount of time in seconds to wait before notifying a timeout.

can you please try updating evaluator to 2.3.0 version and adding the following environment variable to your command
`-e SPLIT_EVALUATOR_GLOBAL_CONFIG='{"startup":{"readyTimeout"=60}}`

Let me know if it worked or if I can help you with anything else

Regards

**Comment by hbqdev** [comment]
Hi @lzrf0cuz 
We will close this issue for now. You can reopen if you still have problem.

Regards
