### ISSUE TITLE
Value undefined for attribute warning

### ISSUE THREAD

**Issue by sorliem** [splitio/split-evaluator#151]
Hi,

I'm using the split evaluator to do treatment requests on our backend and saw this in the logs

```
[WARN]  splitio-engine:value => Value undefined for attribute my_attr doesn't match with expected type.
```

The request:
```
GET /client/get-treatment-with-config?attributes=%7B%22my_attr%22%3A%22my_value%22%7D&key=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx&split-name=my_split_name 200 67 - 0.847 ms
```

Is there something I'm doing wrong? Thank you!

**Comment by hbqdev** [comment]
Hi @sorliem 

The errors means that the value you passed in for attribute my_attr is not the type that is supported.

So either it was not passed as an attribute or its value is "undefined" which is the same as null in Javascript.

Can you please verify that value of the attribute that you're passing in?

Regards

**Comment by sorliem** [comment]
According to the docs, I need to send a json object for the `attributes` url param https://help.split.io/hc/en-us/articles/360020037072-Split-Evaluator#clientget-treatment-with-config

The url encoded `attributes` value from my example above is `%7B%22my_attr%22%3A%22my_value%22%7D` (non url encoded that's `{"my_attr": "my_value"}`), with they key being `my_attr` and the value `my_value`. So I believe I am passing an attribute value and it is non null and not `undefined`. 

I've been able to target off of these attributes in the Split dashboard successfully in the past, so I don't get why I'm getting a warning about it.

**Comment by hbqdev** [comment]
Hi @sorliem 

Can you please share with us your evaluator config and the version that you're using?

Regards,
Tin Tran

**Comment by sorliem** [comment]
Hi @hbqdev - I'm using the docker image `docker.io/splitsoftware/split-evaluator:2.0.6` with only the `SPLIT_EVALUATOR_API_KEY` env var

**Comment by hbqdev** [comment]
Hi @sorliem 
That version is quite old, can you please try again with one of the newer versions and see if the warning still exists?

Regards,

**Comment by sorliem** [comment]
I will try with the latest version (2.3.2) and get back to you, thanks

**Comment by hbqdev** [comment]
Hi @sorliem

We tried to replicate the issue however we could reproduce it
<img width="1223" alt="image" src="https://github.com/splitio/split-evaluator/assets/49971676/333ee459-0f95-4369-b581-48ab2618d5e3">

Can you please tell us the steps you did to reproduce the issue?

Regards
